
logging:
  pattern:
    console: "%d %-5level [${spring.application.name:-}, %X{X-B3-TraceId:-}, %X{X-B3-SpanId:-}] [%thread] %logger : %msg%n"
  level:
    org.springframework: INFO
    org.netflix: INFO
    com.form3: DEBUG


# Hibernate
hibernate:
  dialect: org.hibernate.dialect.PostgreSQL9Dialect
  show_sql: true
  hbm2ddl.auto: none
  packagesToScan: com.form3.payment.domain.model

server:
    servlet-path: /system
    port: 8080

management:
    info:
      git:
        mode: full
    security:
        enabled: false


form3:
  liquibase:
    change-log: liquibase/db.changelog-master.xml
    enabled: false
    drop-first: false
    exit-at-end: false

---

db:
  driver: org.h2.Driver
  url: jdbc:h2:mem:payment;DB_CLOSE_DELAY=-1;LOCK_MODE=1;AUTOCOMMIT=OFF
  username: form3
  password: form3
  maximumPoolSize: 10
  maxLifetime: 30000
  idleTimeout: 20000
  poolSize: 10

spring:
  profiles: local

server.port: 8084
