
logging:
  pattern:
    console: "%d %-5level [${spring.application.name:-}, %X{X-B3-TraceId:-}, %X{X-B3-SpanId:-}] [%thread] %logger : %msg%n"
  level:
    org.springframework: INFO
    org.netflix: INFO
    com.form3: DEBUG

# Hibernate
hibernate:
  dialect: org.hibernate.dialect.PostgreSQL9Dialect
  show_sql: true
  hbm2ddl.auto: none
  packagesToScan: com.form3.payment.domain.model

server:
    servlet-path: /system
    port: 8080


form3:
  liquibase:
    enabled: true
    drop-first: true
    exit-at-end: false

---

spring:
  profiles: local

server.port: 8080


db:
  driver: org.postgresql.Driver
  url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
  username: form3
  password: form3
  maximumPoolSize: 5
  maxLifetime: 30000
  idleTimeout: 20000


form3:
  liquibase:
    enabled: true
    drop-first: true
